### PiCopy Configuration Options:
## Storage-Related Configuration
[STORAGE]
# interval (in seconds) to check for mounted devices
MOUNT_CHECK_INTERVAL=1

# location of mounted drives
MOUNT_LOCATION=/media/pi

# file/folder identifying the destination drive
COPY_DESTINATION_ID=PICOPY_DESTINATION

## File Copying
[FILE_COPYING]
# target file extentions, as comma separated list (case insensitive)
TARGET_FILE_EXTENTIONS=.wav,.txt,.csv

# files and/or folders to ignore while copying, as comma separated list
EXCLUDE_FILES=.Trashes,.fsevents*,System*,.Spotlight*

## System Settings
[SYSTEM]
# button debounce delay
DEBOUNCE_TIME = 0.1
# delay between UI loop iterations
UI_SLEEP_TIME = 0.1